### ISSUE TITLE
Error when running GCP tutorial

### ISSUE THREAD

**Issue by DenisSch** [nextflow-io/rnaseq-nf#6]
I am running the GCP tutorial: https://cloud.google.com/life-sciences/docs/tutorials/nextflow

When executing `./nextflow run rnaseq-nf/main.nf -profile gls`

I receive the following error:

```
N E X T F L O W  ~  version 20.10.0
Launching `rnaseq-nf/main.nf` [hopeful_mccarthy] - revision: 29dd20fd3f
Cannot a find a file system provider for scheme: gs

**Comment by DenisSch** [comment]
Full report

```
Nov-13 04:49:06.872 [main] DEBUG nextflow.cli.Launcher - $> nextflow run rnaseq-nf/main.nf -profile gls
Nov-13 04:49:07.012 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.01.0
Nov-13 04:49:07.027 [main] INFO  nextflow.cli.CmdRun - Launching `rnaseq-nf/main.nf` [loving_mcclintock] - revision: 29dd20fd3f
Nov-13 04:49:07.056 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/dschapir/rnaseq-nf/nextflow.config
Nov-13 04:49:07.057 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/dschapir/rnaseq-nf/nextflow.config
Nov-13 04:49:07.082 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `gls`
Nov-13 04:49:07.602 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [standard, slurm, gs-data, batch, conda, s3-data, docker, gls]
Nov-13 04:49:07.658 [main] DEBUG nextflow.Session - Session uuid: d801f2b1-eb03-46cf-9db1-36dc163bcffc
Nov-13 04:49:07.658 [main] DEBUG nextflow.Session - Run name: loving_mcclintock
Nov-13 04:49:07.659 [main] DEBUG nextflow.Session - Executor pool size: 2
Nov-13 04:49:07.744 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 20.01.0 build 5264
  Created: 12-02-2020 10:14 UTC 
  System: Linux 5.4.49+
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 11.0.9+11-post-Debian-1deb10u1
  Encoding: UTF-8 (UTF-8)
  Process: 12067@cs-869310520897-default-boost-gqj5d [172.17.0.4]
  CPUs: 1 - Mem: 15.6 GB (2.3 GB) - Swap: 768 MB (716 MB)
Nov-13 04:49:07.780 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): /WORK_DIR

Nov-13 04:49:07.781 [main] DEBUG nextflow.Session - Work-dir: gs://nextflowtestcodex/WORK_DIR [null]
Nov-13 04:49:07.781 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/dschapir/rnaseq-nf/bin
Nov-13 04:49:07.876 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Nov-13 04:49:07.955 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Nov-13 04:49:08.130 [main] DEBUG nextflow.Session - Session start invoked
Nov-13 04:49:08.313 [main] WARN  nextflow.NextflowMeta$Preview - DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
Nov-13 04:49:08.317 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Nov-13 04:49:08.329 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: enable for class: nextflow.NextflowMeta
Nov-13 04:49:08.339 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: enable for class: nextflow.NextflowMeta
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at Script_a0d681ec.runScript(Script_a0d681ec:27)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:159)
	at nextflow.script.BaseScript.run(BaseScript.groovy:189)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:225)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:273)
	at nextflow.cli.Launcher.run(Launcher.groovy:460)
	at nextflow.cli.Launcher.main(Launcher.groovy:642)

**Comment by pditommaso** [comment]
What about this ?

```
NXF_MODE=google ./nextflow run rnaseq-nf/main.nf -profile gls
```

**Comment by DenisSch** [comment]
That worked - thank you!

**Comment by DenisSch** [comment]
Unfortunately, the next error message is:
```Missing Google credentials -- make sure your environment defines the GOOGLE_APPLICATION_CREDENTIALS environment variable```

I have performed the steps in the tutorial - it seems like something is still missing

**Comment by DenisSch** [comment]
Update:
The path needs to be defined directly without `{PWD}`
